- name: install nginx server and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: installed
  
  - name: run services
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

