- name: run play
  hosts: web
  vars:
    person1: teja
    person2: ram
  tasks:
  - name: conservation
    ansible.builtin.debug:
      msg: hii {{person1}}, how are you?
      msg: hello {{person2}}, im fine {{person1}}. how are you ?

  # - name: run play-2
  #   ansible.builtin.debug:
  #     msg: run the play-2