- name: create loops
  hosts: local
  connection: local
  tasks:
  - name: running the message
    ansible.builtin.debug:
      msg: Hello {{item}}, how are you {{item}}
    loop:
    - teja
    - nimmi
    - chintu